spring:
  application:
    name: TaskBot

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_system
    hikari:
      username: postgres
      password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

taskbot:
  name-bot: "TaskBot"
  bot-token: "7447286184:AAFIDdGk6TqaPgFaWmOcazb2N_ecHGu-3vc"