spring:
  application:
    name: TaskBot

  datasource:
    url: jdbc:postgresql://TaskBotContainer:5432/TaskBot
    hikari:
      username: postgres
      password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8443

taskbot:
  name-bot: "TaskBot"
  bot-token: ${BOT_TOKEN}
  provider: "185.105.89.194"